### ISSUE TITLE
Support Port

### ISSUE THREAD

**Issue by ubergesundheit** [sensebox/ttn-osem-application#1]
The json submitted by ttn contains the LoRa port.
Users should be able to specify to listen only to a certain port or if the port value should be ignored.

**Comment by noerw** [comment]
e744f8eb100aa83b5dd2db32da0e9aaab8c65cd6

the first box matching the port for a given `dev_id` and `app_id` is used for the request.
if no box is matched, and a box matches the IDs but has no port specified, this box is used.

possible TODO: submit measurements to all matching boxes. OR: ensure that dev_id, app_id and port combinations are unique?
